CREATE DATABASE CACHARRERIA;
GO

USE CACHARRERIA;
GO

--Principales
CREATE TABLE PROVEEDORES
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	empresa VARCHAR(30) NOT NULL,
	telefono VARCHAR(10)
);


CREATE TABLE COMPONENTES
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	descripcion VARCHAR(100) NOT NULL,
	tipo VARCHAR(30) NOT NULL
);

CREATE TABLE CATEGORIAS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
    descripcion VARCHAR(100)
);

CREATE TABLE SEDES
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	direccion VARCHAR(100) NOT NULL,
	enfoque VARCHAR(30)
);

CREATE TABLE CLIENTES
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	telefono VARCHAR(10)
);


--Secundarias
CREATE TABLE PRODUCTOS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	stock INT NOT NULL CHECK (stock >= 0),
	precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0),
	relevancia INT,
	id_Categoria INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(id) 
	
);

CREATE TABLE TRABAJADORES
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	cargo VARCHAR(30) NOT NULL,
	telefono VARCHAR(10),
	sueldo DECIMAL(10,2) NOT NULL CHECK (sueldo >= 0),
	fecha_ingreso DATE NOT NULL,
	id_sede INT NOT NULL FOREIGN KEY REFERENCES SEDES(id) 
);

CREATE TABLE SUSCRIPCIONES
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	tipo VARCHAR(30) NOT NULL,
	estado VARCHAR(30) NOT NULL,
	fecha_inicio DATE NOT NULL,
	fecha_finalizacion DATE NOT NULL,
	costo DECIMAL(10,2) NOT NULL CHECK (costo >= 0),
	id_cliente INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(id) 
);

CREATE TABLE VENTAS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	monto DECIMAL(10,2) NOT NULL CHECK (monto >= 0),
	fecha DATE NOT NULL,
	metodo_pago VARCHAR(20) NOT NULL,
	id_cliente INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(id), 
	id_trabajador INT NOT NULL FOREIGN KEY REFERENCES TRABAJADORES(id) 

);


CREATE TABLE PRODUCTOS_VENTAS
( 
	id INT IDENTITY(1,1) PRIMARY KEY,
	cantidad INT NOT NULL CHECK (cantidad > 0),
	id_producto INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(id),
	id_venta INT NOT NULL FOREIGN KEY REFERENCES VENTAS(id) 
		
);

CREATE TABLE PROVEEDORES_PRODUCTOS
(	
	id INT IDENTITY(1,1) PRIMARY KEY,
	id_producto INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(id),
	id_proveedor INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(id)


);

CREATE TABLE COMPONENTES_PRODUCTOS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	cantidad INT NOT NULL CHECK (cantidad > 0),
	id_producto INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(id),
	id_componente INT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(id) 
);